#!name=AdvertisingScriptSupplement
#!desc=补充去广告策略
#!author=kenny273

[Rule]
DOMAIN,118.89.204.198,REJECT
DOMAIN,d.image.i4.cn,REJECT
DOMAIN,hub5btmain.v6.shub.sandai.net,REJECT
DOMAIN,hub5emu.v6.shub.sandai.net,REJECT
DOMAIN,hub5idx.v6.shub.sandai.net,REJECT
DOMAIN,im.tieba.baidu.com,REJECT
DOMAIN,ntb.lanjie100.com,REJECT
DOMAIN,open.e.kuaishou.com,REJECT
DOMAIN,ulogs.umeng.com,REJECT
DOMAIN-KEYWORD,118.89.204.198,REJECT
DOMAIN-KEYWORD,-ad-sign.byteimg.com,REJECT
DOMAIN-KEYWORD,asiad.byteactivity,REJECT
DOMAIN-KEYWORD,baihemob,REJECT
DOMAIN-KEYWORD,beizi.biz,REJECT
DOMAIN-KEYWORD,pangolin,REJECT
DOMAIN-KEYWORD,pangolin.snssdk.com,REJECT
DOMAIN-KEYWORD,pglstatp,REJECT
DOMAIN-KEYWORD,-tos.pstatp.com,REJECT
DOMAIN-KEYWORD,video-cn.snssdk.com,REJECT
DOMAIN-KEYWORD,volc,REJECT
DOMAIN-SUFFIX,4009997658.com,REJECT
DOMAIN-SUFFIX,abbyychina.com,REJECT
DOMAIN-SUFFIX,bartender.cc,REJECT
DOMAIN-SUFFIX,betterzip.net,REJECT
DOMAIN-SUFFIX,betterzipcn.com,REJECT
DOMAIN-SUFFIX,beyondcompare.cc,REJECT
DOMAIN-SUFFIX,bingdianhuanyuan.cn,REJECT
DOMAIN-SUFFIX,chemdraw.com.cn,REJECT
DOMAIN-SUFFIX,cjmakeding.com,REJECT
DOMAIN-SUFFIX,cjmkt.com,REJECT
DOMAIN-SUFFIX,codesoftchina.com,REJECT
DOMAIN-SUFFIX,coreldrawchina.com,REJECT
DOMAIN-SUFFIX,crossoverchina.com,REJECT
DOMAIN-SUFFIX,dongmansoft.com,REJECT
DOMAIN-SUFFIX,earmasterchina.cn,REJECT
DOMAIN-SUFFIX,easyrecoverychina.com,REJECT
DOMAIN-SUFFIX,ediuschina.com,REJECT
DOMAIN-SUFFIX,flstudiochina.com,REJECT
DOMAIN-SUFFIX,formysql.com,REJECT
DOMAIN-SUFFIX,guitarpro.cc,REJECT
DOMAIN-SUFFIX,huishenghuiying.com.cn,REJECT
DOMAIN-SUFFIX,hypersnap.net,REJECT
DOMAIN-SUFFIX,iconworkshop.cn,REJECT
DOMAIN-SUFFIX,imindmap.cc,REJECT
DOMAIN-SUFFIX,jihehuaban.com.cn,REJECT
DOMAIN-SUFFIX,keyshot.cc,REJECT
DOMAIN-SUFFIX,kingdeecn.cn,REJECT
DOMAIN-SUFFIX,logoshejishi.com,REJECT
DOMAIN-SUFFIX,luping.net.cn,REJECT
DOMAIN-SUFFIX,mairuan.cn,REJECT
DOMAIN-SUFFIX,mairuan.com,REJECT
DOMAIN-SUFFIX,mairuan.com.cn,REJECT
DOMAIN-SUFFIX,mairuan.net,REJECT
DOMAIN-SUFFIX,mairuanwang.com,REJECT
DOMAIN-SUFFIX,makeding.com,REJECT
DOMAIN-SUFFIX,mathtype.cn,REJECT
DOMAIN-SUFFIX,mindmanager.cc,REJECT
DOMAIN-SUFFIX,mindmanager.cn,REJECT
DOMAIN-SUFFIX,mindmapper.cc,REJECT
DOMAIN-SUFFIX,mycleanmymac.com,REJECT
DOMAIN-SUFFIX,nicelabel.cc,REJECT
DOMAIN-SUFFIX,ntfsformac.cc,REJECT
DOMAIN-SUFFIX,ntfsformac.cn,REJECT
DOMAIN-SUFFIX,overturechina.com,REJECT
DOMAIN-SUFFIX,passwordrecovery.cn,REJECT
DOMAIN-SUFFIX,pdfexpert.cc,REJECT
DOMAIN-SUFFIX,photozoomchina.com,REJECT
DOMAIN-SUFFIX,shankejingling.com,REJECT
DOMAIN-SUFFIX,u3.ucweb.com,REJECT
DOMAIN-SUFFIX,ultraiso.net,REJECT
DOMAIN-SUFFIX,vegaschina.cn,REJECT
DOMAIN-SUFFIX,xmindchina.net,REJECT
DOMAIN-SUFFIX,xshellcn.com,REJECT
DOMAIN-SUFFIX,yihuifu.cn,REJECT
DOMAIN-SUFFIX,yuanchengxiezuo.com,REJECT
DOMAIN-SUFFIX,zbrushcn.com,REJECT
DOMAIN-SUFFIX,zhzzx.com,REJECT
IP-CIDR,10.0.0.0/8,DIRECT
IP-CIDR,118.89.204.198/32,REJECT
IP-CIDR,127.0.0.0/8,DIRECT
IP-CIDR,17.0.0.0/8,DIRECT
IP-CIDR,17.188.128.0/18,DIRECT
IP-CIDR,17.188.20.0/23,DIRECT
IP-CIDR,17.249.0.0/16,DIRECT
IP-CIDR,17.252.0.0/16,DIRECT
IP-CIDR,17.57.144.0/22,DIRECT
IP-CIDR,172.16.0.0/12,DIRECT
IP-CIDR,180.76.76.200/32,REJECT
IP-CIDR,180.76.76.200/32,REJECT
IP-CIDR,182.254.116.0/24,DIRECT
IP-CIDR,192.168.0.0/16,DIRECT
IP-CIDR,203.107.1.1/24,REJECT
IP-CIDR,224.0.0.0/24,DIRECT
USER-AGENT,AVOS*,REJECT

[URL Rewrite]
(^https?:\/\/app\.biliintl.com\/intl\/.+)(&sim_code=\d+)(.+)-302$1$3
^https://api.bilibili.com/pgc/season/player/cards - REJECT-DICT
^https://app.bilibili.com/x/v2/search/defaultwords - REJECT-DICT
^https://app.bilibili.com/x/v2/splash/show - REJECT-DICT
^https:\/\/api\.zhihu\.com\/(moments\/lastread|drama\/hot-drama-list) REJECT-DICT
^https:\/\/api\.zhihu\.com\/comment_v5\/answers\/\d+\/list-headers REJECT-DICT
^https:\/\/api\.zhihu\.com\/commercial_api\/(banners_v3\/app_topstory_banner|launch_v2|real_time_launch_v2) REJECT-DICT
^https:\/\/api\.zhihu\.com\/distribute\/rhea\/qa_ad_card\/h5\/recommendation\? REJECT-DICT
^https:\/\/api\.zhihu\.com\/feed\/render\/revisit\/current_reading REJECT-DICT
^https:\/\/api\.zhihu\.com\/me\/guides REJECT-DICT
^https:\/\/api\.zhihu\.com\/root\/window REJECT-DICT
^https:\/\/api\.zhihu\.com\/search\/preset_words REJECT-DICT
^https:\/\/api\.zhihu\.com\/unlimited\/go\/my_card REJECT
^https:\/\/api\.zhihu\.com\/v5\.1\/topics\/answer\/\d+\/relation REJECT-DICT
^https:\/\/appcloud2\.zhihu\.com\/v3\/resource\?group_name=mp REJECT-DICT
^https:\/\/www\.zhihu\.com\/api\/v4/(questions|anwsers)\/\d+/related-readings REJECT
^https:\/\/www\.zhihu\.com\/api\/v4\/hot_recommendation REJECT
^https:\/\/www\.zhihu\.com\/api\/v4\/mcn\/v2\/linkcards\? REJECT
^https:\/\/www\.zhihu\.com\/api\/v4\/search\/related_queries\/article\/\d+ REJECT-DICT
^https:\/\/www\.zhihu\.com\/appview\/v2\/zhmore REJECT
^https:\/\/www\.zhihu\.com\/commercial_api\/banners_v3\/mobile_banner REJECT
^https:\/\/zhuanlan\.zhihu\.com\/api\/articles\/\d+\/recommendation REJECT
^https?://api\.zhihu\.com/\w+/\d+/comments/featured-comment-ad REJECT
^https?://api\.zhihu\.com/ad REJECT
^https?://api\.zhihu\.com/appview/api/v\d/answers/\d+/recommendations REJECT
^https?://api\.zhihu\.com/commercial_api/ REJECT
^https?://weibointl\.api\.weibo\.cn/portal\.php\?a=get_coopen_ads REJECT 
^https?://www\.zhihu\.com/api/v\d/answers/\d+/recommendations REJECT
^https?:\/\/api\.bilibili\.com\/pgc\/season\/app\/related\/recommend\? - REJECT-DICT
^https?:\/\/api\.bilibili\.com\/x\/vip\/ads\/material\/report - REJECT-DICT
^https?:\/\/api\.coolapk\.com\/v6\/search\?.*type=hotSearch REJECT-DICT
^https?:\/\/api\.vc\.bilibili\.com\/search_svr\/v\d\/Search\/recommend_words - REJECT
^https?:\/\/api\.vc\.bilibili\.com\/topic_svr\/v1\/topic_svr - REJECT-DICT
^https?:\/\/api\.weibo\.cn\/\d\/cardlist\?v_f=.*Weibo_intl REJECT-DICT 
^https?:\/\/api\.zhihu\.com\/brand\/question\/\d+/card\? REJECT-DICT
^https?:\/\/api\.zhihu\.com\/feed\/render\/revisit\/current_reading REJECT-DICT
^https?:\/\/api\.zhihu\.com\/feed\/render\/revisit\/tag_config REJECT-DICT
^https?:\/\/api\.zhihu\.com\/me\/guides REJECT-DICT
^https?:\/\/api\.zhihu\.com\/moments\/recent REJECT-DICT
^https?:\/\/api\.zhihu\.com\/moments\/tab_v2 REJECT-DICT
^https?:\/\/app\.bilibili\.com\/bilibili\.app\.interface\.v1\.Search\/Default - REJECT
^https?:\/\/app\.bilibili\.com\/x\/resource\/ip - REJECT
^https?:\/\/app\.bilibili\.com\/x\/resource\/top\/activity - REJECT-DICT
^https?:\/\/bbs-api\.miyoushe\.com\/apihub\/api\/getAppSplash REJECT
^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/ad\/weibointl\? REJECT-DICT 
^https?:\/\/manga\.bilibili\.com\/twirp\/comic\.v\d\.Comic\/(Flash|ListFlash) - REJECT-DICT
^https?:\/\/quanguo\.mygolbs\.com:8081\/MyBusServer\/servlet\/MyGoServer\.HttpPool\.HttpHandlerServlet REJECT-200 
^https?:\/\/weibointl\.api\.weibo\.c(n|om)\/portal\.php\?a=hot_search_users REJECT-DICT
^https?:\/\/www\.zhihu\.com\/api\/v\d\/answers\/\d+\/recommendations REJECT-DICT
^https?:\/\/www\.zhihu\.com\/api\/v\d+\/brand\/question/\d+/card\? REJECT-DICT

[Script]
12306 = type=http-response,pattern=^https?:\/\/ad\.12306\.cn\/ad\/ser\/getAdList,requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/12306.js
biliad=type=http-response,pattern=^https?:\/\/i.\.hdslb\.com\/bfs\/subtitle\/.+\.json$,requires-body=1,script-path=https://github.com/deezertidal/private/raw/master/js-backup/Rewrite/Function/Bilibili_CC.conf
biliad1=type=http-response,pattern=^https?:\/\/api\.(bilibili|biliapi)\.(com|net)\/pgc\/page\/cinema\/tab\?,requires-body=1,script-path=https://raw.githubusercontent.com/deezertidal/private/master/js-backup/Script/bilibili_json.js
biliad2=type=http-response,pattern=^https:\/\/app\.bilibili\.com\/x\/v2\/splash\/list,requires-body=1,script-path=https://raw.githubusercontent.com/deezertidal/private/master/js-backup/Script/bilibili_json.js
biliad3=type=http-response,pattern=^https?:\/\/app\.bilibili\.com\/x\/resource\/show\/skin\?,requires-body=1,script-path=https://raw.githubusercontent.com/deezertidal/private/master/js-backup/Script/bilibili_json.js
biliad4=type=http-response,pattern=^https?:\/\/app\.bilibili\.com\/x\/v2\/account\/myinfo\?,requires-body=1,script-path=https://raw.githubusercontent.com/deezertidal/private/master/js-backup/Script/bilibili_json.js
biliad5=type=http-response,pattern=^https://app.bilibili.com/x/v2/search/square,requires-body=1,script-path=https://raw.githubusercontent.com/deezertidal/private/master/js-backup/Script/bilibili_json.js
biliad6=type=http-response,pattern=^https?:\/\/app\.bilibili\.com\/x\/v2\/feed\/index,requires-body=1,script-path=https://raw.githubusercontent.com/deezertidal/private/master/js-backup/Script/bilibili_json.js
biliad7=type=http-response,pattern=^https?:\/\/api\.(bilibili|biliapi)\.(com|net)\/pgc\/page\/bangumi,requires-body=1,script-path=https://raw.githubusercontent.com/deezertidal/private/master/js-backup/Script/bilibili_json.js
biliad8=type=http-response,pattern=^https?:\/\/api\.live\.bilibili\.com\/xlive\/app-room\/v1\/index\/getInfoByRoom,requires-body=1,script-path=https://raw.githubusercontent.com/deezertidal/private/master/js-backup/Script/bilibili_json.js
biliad9=type=http-response,pattern=^https?:\/\/api\.vc\.bilibili\.com\/dynamic_svr\/v1\/dynamic_svr\/dynamic_(history|new)\?,requires-body=1,script-path=https://raw.githubusercontent.com/deezertidal/private/master/js-backup/Script/bilibili_json.js
biliad10=type=http-response,pattern=^https?:\/\/app\.bilibili\.com\/x\/resource\/show\/tab,requires-body=1,script-path=https://raw.githubusercontent.com/deezertidal/private/master/js-backup/Script/bilibili_json.js
biliad11=type=http-response,pattern=^https?:\/\/app\.bilibili\.com\/x\/v2\/account\/mine,requires-body=1,script-path=https://raw.githubusercontent.com/deezertidal/private/master/js-backup/Script/bilibili_json.js
biliad12=type=http-response,pattern=^https:\/\/app\.bilibili\.com\/bilibili\.app\.(view\.v1\.View\/View|dynamic\.v2\.Dynamic\/DynAll)$,requires-body=1,script-path=https://raw.githubusercontent.com/app2smile/rules/master/js/bilibili-proto.js
biliad13=type=http-response,pattern=^https://app\.bilibili\.com/bilibili\.app\.dynamic\.v2\.Dynamic/DynAll$,requires-body=1,script-path=https://raw.githubusercontent.com/yjqiang/surge_scripts/main/scripts/bilibili/bilibili_dynamic.js
coolapk=type=http-response,pattern=^https?:\/\/api.coolapk.com\/v6\/main\/init,requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/coolapk.js
coolapk1=type=http-response,pattern=^https?:\/\/api.coolapk.com\/v6\/main\/indexV8,requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/coolapk.js
coolapk2=type=http-response,pattern=^https?:\/\/api.coolapk.com\/v6\/feed\/replyList,requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/coolapk.js
coolapk3=type=http-response,pattern=^https?:\/\/api.coolapk.com\/v6\/feed\/detail,requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/coolapk.js
coolapk4=type=http-response,pattern=^https?:\/\/api.coolapk.com\/v6\/dataList,requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/coolapk.js
Mygolbus = type=http-response,pattern=^https?:\/\/wx\.mygolbs\.com\/WxBusServer\/ApiData\.do,requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/zhangshanggongjiao.js
WeChatOfficialAccounts=type=http-response,pattern=^https?:\/\/mp\.weixin\.qq\.com\/mp\/getappmsgad,requires-body=1,script-path=https://raw.githubusercontent.com/NobyDa/Script/master/QuantumultX/File/Wechat.js
WeiboIntljson = type=http-response,pattern=^https?:\/\/weibointl\.api\.weibo\.cn\/portal\.php\?a=user_center,requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js
WeiboIntljson2 = type=http-response,pattern=^https?:\/\/weibointl\.api\.weibo\.cn\/portal\.php\?a=search_topic,requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js
WeiboIntljson3 = type=http-response,pattern=^https?:\/\/weibointl\.api\.weibo\.cn\/portal\.php\?a=open_app,requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js
WeiboIntljson4 = type=http-response,pattern=^https?:\/\/weibointl\.api\.weibo\.c(n|om)\/portal\.php.*get_coopen_ads,requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js
WeiboIntljson5 = type=http-response,pattern=^https?:\/\/weibointl\.api\.weibo\.c(n|om)\/portal\.php.*feed&a=trends,requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js
zheye=type=http-response,pattern=^https?:\/\/www\.zhihu\.com\/api\/v\d\/articles\/\d+\/recommendation\?,requires-body=1,script-path=https://gist.githubusercontent.com/blackmatrix7/f5f780d0f56b319b6ad9848fd080bb18/raw/zheye.min.js
zheye1=type=http-response,pattern=^https?:\/\/api\.zhihu\.com\/next-(data|bff|render),requires-body=1,script-path=https://gist.githubusercontent.com/blackmatrix7/f5f780d0f56b319b6ad9848fd080bb18/raw/zheye.min.js
zheye2=type=http-response,pattern=^https?:\/\/api\.zhihu\.com\/moments_v3\?,requires-body=1,script-path=https://gist.githubusercontent.com/blackmatrix7/f5f780d0f56b319b6ad9848fd080bb18/raw/zheye.min.js
zheye3=type=http-response,pattern=^https?:\/\/api\.zhihu\.com\/feed\/render\/tab\/config,requires-body=1,script-path=https://gist.githubusercontent.com/blackmatrix7/f5f780d0f56b319b6ad9848fd080bb18/raw/zheye.min.js
zheye4=type=http-response,pattern=^https:\/\/api\.zhihu\.com\/topstory\/recommend,requires-body=1,script-path=https://gist.githubusercontent.com/blackmatrix7/f5f780d0f56b319b6ad9848fd080bb18/raw/zheye.min.js
zheye5=type=http-response,pattern=^https?:\/\/appcloud2\.zhihu\.com\/v\d+\/resource,requires-body=1,script-path=https://gist.githubusercontent.com/blackmatrix7/f5f780d0f56b319b6ad9848fd080bb18/raw/zheye.min.js

[MITM]
hostname= %APPEND% ad.12306.cn,api.live.bilibili.com,api.vc.bilibili.com,api.bilibili.com,bbs-api.miyoushe.com,manga.bilibili.com,grpc.biliapi.net,api.biliapi.net,-broadcast.chat.bilibili.com,-*cdn*.biliapi.net,-*tracker*.biliapi.net
