#!name=PoliciesSupplement
#!desc=策略补充
#!author=kenny273

[General]
skip-proxy = %APPEND% captive.apple.com,e.crashlytics.com,gate.lagou.com,login-service.mobile-bank.psbc.com,mobile-bank.psbc.com,seed-sequoia.siri.apple.com,sequoia.apple.com,www.abchina.com.cn,www.baidu.com,www.shanbay.com,wxh.wo.cn,yunbusiness.ccb.com

[Rule]
DOMAIN,118.89.204.198,REJECT
DOMAIN,ad.12306.cn,REJECT
DOMAIN,d.image.i4.cn,REJECT
DOMAIN,emby.aca.best,🎬 国际流媒体
DOMAIN,hub5btmain.v6.shub.sandai.net,REJECT
DOMAIN,hub5emu.v6.shub.sandai.net,REJECT
DOMAIN,hub5idx.v6.shub.sandai.net,REJECT
DOMAIN,im.tieba.baidu.com,REJECT
DOMAIN,ntb.lanjie100.com,REJECT
DOMAIN,porn.aca.best,🎬 国际流媒体
DOMAIN-KEYWORD,118.89.204.198,REJECT
DOMAIN-KEYWORD,-ad-sign.byteimg.com,REJECT
DOMAIN-KEYWORD,asiad.byteactivity,REJECT
DOMAIN-KEYWORD,baihemob,REJECT
DOMAIN-KEYWORD,beizi.biz,REJECT
DOMAIN-KEYWORD,pangolin,REJECT
DOMAIN-KEYWORD,pangolin.snssdk.com,REJECT
DOMAIN-KEYWORD,pglstatp,REJECT
DOMAIN-KEYWORD,-tos.pstatp.com,REJECT
DOMAIN-KEYWORD,video-cn.snssdk.com,REJECT
DOMAIN-KEYWORD,volc,REJECT
DOMAIN-SUFFIX,4009997658.com,REJECT
DOMAIN-SUFFIX,abbyychina.com,REJECT
DOMAIN-SUFFIX,bartender.cc,REJECT
DOMAIN-SUFFIX,betterzip.net,REJECT
DOMAIN-SUFFIX,betterzipcn.com,REJECT
DOMAIN-SUFFIX,beyondcompare.cc,REJECT
DOMAIN-SUFFIX,bingdianhuanyuan.cn,REJECT
DOMAIN-SUFFIX,chemdraw.com.cn,REJECT
DOMAIN-SUFFIX,cjmakeding.com,REJECT
DOMAIN-SUFFIX,cjmkt.com,REJECT
DOMAIN-SUFFIX,codesoftchina.com,REJECT
DOMAIN-SUFFIX,coreldrawchina.com,REJECT
DOMAIN-SUFFIX,crossoverchina.com,REJECT
DOMAIN-SUFFIX,ctrmi.cn,REJECT
DOMAIN-SUFFIX,dongmansoft.com,REJECT
DOMAIN-SUFFIX,earmasterchina.cn,REJECT
DOMAIN-SUFFIX,easyrecoverychina.com,REJECT
DOMAIN-SUFFIX,ediuschina.com,REJECT
DOMAIN-SUFFIX,flstudiochina.com,REJECT
DOMAIN-SUFFIX,formysql.com,REJECT
DOMAIN-SUFFIX,guitarpro.cc,REJECT
DOMAIN-SUFFIX,huishenghuiying.com.cn,REJECT
DOMAIN-SUFFIX,hypersnap.net,REJECT
DOMAIN-SUFFIX,iconworkshop.cn,REJECT
DOMAIN-SUFFIX,imindmap.cc,REJECT
DOMAIN-SUFFIX,jihehuaban.com.cn,REJECT
DOMAIN-SUFFIX,keyshot.cc,REJECT
DOMAIN-SUFFIX,kingdeecn.cn,REJECT
DOMAIN-SUFFIX,logoshejishi.com,REJECT
DOMAIN-SUFFIX,luping.net.cn,REJECT
DOMAIN-SUFFIX,mairuan.cn,REJECT
DOMAIN-SUFFIX,mairuan.com,REJECT
DOMAIN-SUFFIX,mairuan.com.cn,REJECT
DOMAIN-SUFFIX,mairuan.net,REJECT
DOMAIN-SUFFIX,mairuanwang.com,REJECT
DOMAIN-SUFFIX,makeding.com,REJECT
DOMAIN-SUFFIX,mathtype.cn,REJECT
DOMAIN-SUFFIX,miaozhen.com,REJECT
DOMAIN-SUFFIX,mindmanager.cc,REJECT
DOMAIN-SUFFIX,mindmanager.cn,REJECT
DOMAIN-SUFFIX,mindmapper.cc,REJECT
DOMAIN-SUFFIX,misakaf.org,🎬 国际流媒体
DOMAIN-SUFFIX,mycleanmymac.com,REJECT
DOMAIN-SUFFIX,nicelabel.cc,REJECT
DOMAIN-SUFFIX,ntfsformac.cc,REJECT
DOMAIN-SUFFIX,ntfsformac.cn,REJECT
DOMAIN-SUFFIX,overturechina.com,REJECT
DOMAIN-SUFFIX,passwordrecovery.cn,REJECT
DOMAIN-SUFFIX,pdfexpert.cc,REJECT
DOMAIN-SUFFIX,photozoomchina.com,REJECT
DOMAIN-SUFFIX,shankejingling.com,REJECT
DOMAIN-SUFFIX,shark-tracer.netease.com,REJECT
DOMAIN-SUFFIX,shuzilm.cn,REJECT
DOMAIN-SUFFIX,u3.ucweb.com,REJECT
DOMAIN-SUFFIX,ultraiso.net,REJECT
DOMAIN-SUFFIX,umeng.com,REJECT
DOMAIN-SUFFIX,uyunad.com,REJECT
DOMAIN-SUFFIX,vegaschina.cn,REJECT
DOMAIN-SUFFIX,xmindchina.net,REJECT
DOMAIN-SUFFIX,xshellcn.com,REJECT
DOMAIN-SUFFIX,yihuifu.cn,REJECT
DOMAIN-SUFFIX,yuanchengxiezuo.com,REJECT
DOMAIN-SUFFIX,zbrushcn.com,REJECT
DOMAIN-SUFFIX,zhzzx.com,REJECT

[URL Rewrite]
^https://api.bilibili.com/pgc/season/player/cards - REJECT-DICT
^https://app.bilibili.com/x/v2/splash/show - REJECT-DICT
^https?:\/\/(app\.bilibili\.com|grpc\.biliapi\.net)\/bilibili\.app\.interface\.v1\.Search\/Default - REJECT
^https?:\/\/(preload-click|preload-impression)\.uve\.weibo\.com\/(interface\/wbpullad\/wbpullad_click\.php|wbapplua\/get_wbpullad_log\.lua) - REJECT
^https?:\/\/api\.bilibili\.com\/pgc\/activity\/deliver\/material\/receive - REJECT-DICT
^https?:\/\/api\.bilibili\.com\/pgc\/season\/player\/ogv\/cards - REJECT-DICT
^https?:\/\/api\.bilibili\.com\/x\/vip\/ads\/material\/report - REJECT-DICT
^https?:\/\/api\.coolapk\.com\/v6\/search\?.*type=hotSearch - REJECT-DICT
^https?:\/\/api\.weibo\.cn\/\d\/!\/huati\/discovery_home_bottom_getdotinfo - REJECT-DICT
^https?:\/\/api\.weibo\.cn\/\d\/ad\/preload - REJECT-DICT
^https?:\/\/api\.weibo\.cn\/\d\/cardlist\?v_f=.*Weibo_intl - REJECT-DICT
^https?:\/\/api\.weibo\.cn\/\d\/profile\/recommend_popuser - REJECT-DICT
^https?:\/\/app\.bilibili\.com\/x\/resource\/ip - REJECT
^https?:\/\/bbs-api\.miyoushe\.com\/apihub\/api\/getAppSplash - REJECT
^https?:\/\/boot.*weibo\.com\/v\d\/ad\/realtime - REJECT-200
^https?:\/\/m?api\.weibo\.c(n|om)\/\d/push/daily - REJECT-DICT
^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/ad\/weibointl\? - REJECT-DICT
^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/hot\/hours_spotlight - REJECT-DICT
^https?:\/\/manga\.bilibili\.com\/twirp\/comic\.v\d\.Comic\/(Flash|ListFlash|GetActivityTab) - REJECT-DICT
^https?:\/\/quanguo\.mygolbs\.com:8081\/MyBusServer\/servlet\/MyGoServer\.HttpPool\.HttpHandlerServlet - REJECT-200 
^https?:\/\/sdkapp\.uve\.weibo\.com\/interface\/sdk\/sdkconfig\.php - REJECT
^https?:\/\/weibointl\.api\.weibo\.c(n|om)\/portal\.php\?a=hot_search_users - REJECT-DICT

[Script]
12306 = type=http-request, pattern=^https?:\/\/ad\.12306\.cn\/ad\/ser\/getAdList, script-path=https://github.com/ddgksf2013/Scripts/raw/master/12306.js, requires-body=true, max-size=-1, timeout=60
bilibili_json = type=http-response, pattern=^https?:\/\/api\.bili(api|bili)\.(net|com)\/pgc\/season\/app\/related\/recommend\?, script-path=https://github.com/ddgksf2013/Scripts/raw/master/bilibili_json.js, requires-body=true, max-size=-1, timeout=60
bilibili_json1 = type=http-response, pattern=^https://app.bilibili.com/x/v2/search/square, script-path=https://github.com/ddgksf2013/Scripts/raw/master/bilibili_json.js, requires-body=true, max-size=-1, timeout=60
bilibili_json2 = type=http-response, pattern=^https:\/\/app\.bilibili\.com\/x\/v2\/splash\/list, script-path=https://github.com/ddgksf2013/Scripts/raw/master/bilibili_json.js, requires-body=true, max-size=-1, timeout=60
bilibili_json3 = type=http-response, pattern=^https?:\/\/api\.(bilibili|biliapi)\.(com|net)\/pgc\/page\/bangumi, script-path=https://github.com/ddgksf2013/Scripts/raw/master/bilibili_json.js, requires-body=true, max-size=-1, timeout=60
bilibili_json4 = type=http-response, pattern=^https?:\/\/api\.(bilibili|biliapi)\.(com|net)\/pgc\/page\/cinema\/tab\?, script-path=https://github.com/ddgksf2013/Scripts/raw/master/bilibili_json.js, requires-body=true, max-size=-1, timeout=60
bilibili_json5 = type=http-response, pattern=^https?:\/\/api\.live\.bilibili\.com\/xlive\/app-interface\/v2\/index\/feed, script-path=https://github.com/ddgksf2013/Scripts/raw/master/bilibili_json.js, requires-body=true, max-size=-1, timeout=60
bilibili_json6 = type=http-response, pattern=^https?:\/\/api\.live\.bilibili\.com\/xlive\/app-room\/v1\/index\/getInfoByRoom, script-path=https://github.com/ddgksf2013/Scripts/raw/master/bilibili_json.js, requires-body=true, max-size=-1, timeout=60
bilibili_json7 = type=http-response, pattern=^https?:\/\/api\.live\.bilibili\.com\/xlive\/e-commerce-interface\/v\d\/ecommerce-user\/get_shopping_info\?, script-path=https://github.com/ddgksf2013/Scripts/raw/master/bilibili_json.js, requires-body=true, max-size=-1, timeout=60
bilibili_json8 = type=http-response, pattern=^https?:\/\/app\.bilibili\.com\/x\/resource\/show\/tab, script-path=https://github.com/ddgksf2013/Scripts/raw/master/bilibili_json.js, requires-body=true, max-size=-1, timeout=60
bilibili_json9 = type=http-response, pattern=^https?:\/\/app\.bilibili\.com\/x\/resource\/top\/activity, script-path=https://github.com/ddgksf2013/Scripts/raw/master/bilibili_json.js, requires-body=true, max-size=-1, timeout=60
bilibili_json10 = type=http-response, pattern=^https?:\/\/app\.bilibili\.com\/x\/v2\/account\/mine, script-path=https://github.com/ddgksf2013/Scripts/raw/master/bilibili_json.js, requires-body=true, max-size=-1, timeout=60
bilibili_json11 = type=http-response, pattern=^https?:\/\/app\.bilibili\.com\/x\/v2\/account\/myinfo\?, script-path=https://github.com/ddgksf2013/Scripts/raw/master/bilibili_json.js, requires-body=true, max-size=-1, timeout=60
bilibili_json12 = type=http-response, pattern=^https?:\/\/app\.bilibili\.com\/x\/v2\/feed\/index, script-path=https://github.com/ddgksf2013/Scripts/raw/master/bilibili_json.js, requires-body=true, max-size=-1, timeout=60
bilibili_proto_beta = type=http-response, pattern=^https:\/\/(grpc\.biliapi\.net|app\.bilibili\.com)\/bilibili\.app\.interface\.v1\.Teenagers\/ModeStatus, script-path=https://github.com/ddgksf2013/Scripts/raw/master/bilibili_proto_beta.js, requires-body=true, binary-body-mode=true, max-size=-1, timeout=60
bilibili_proto_beta1 = type=http-response, pattern=^https?:\/\/(app\.bilibili\.com|grpc\.biliapi\.net)\/bilibili\.app\.(view|viewunite)\.v1\.View\/(View|TFInfo)$, script-path=https://github.com/ddgksf2013/Scripts/raw/master/bilibili_proto_beta.js, requires-body=true, binary-body-mode=true, max-size=-1, timeout=60
bilibili_proto_beta2 = type=http-response, pattern=^https?:\/\/(app\.bilibili\.com|grpc\.biliapi\.net)\/bilibili\.app\.dynamic\.v2\.Dynamic\/Dyn(All|Video)$, script-path=https://github.com/ddgksf2013/Scripts/raw/master/bilibili_proto_beta.js, requires-body=true, binary-body-mode=true, max-size=-1, timeout=60
bilibili_proto_beta3 = type=http-response, pattern=^https?:\/\/(app\.bilibili\.com|grpc\.biliapi\.net)\/bilibili\.community\.service\.dm\.v1\.DM\/(DmView|DmSegMobile), script-path=https://github.com/ddgksf2013/Scripts/raw/master/bilibili_proto_beta.js, requires-body=true, binary-body-mode=true, max-size=-1, timeout=60
bilibili_proto_beta4 = type=http-response, pattern=^https?:\/\/(grpc\.biliapi\.net|app\.bilibili\.com)\/bilibili\.polymer\.app\.search\.v1\.Search\/SearchAll$, script-path=https://github.com/ddgksf2013/Scripts/raw/master/bilibili_proto_beta.js, requires-body=true, binary-body-mode=true, max-size=-1, timeout=60
coolapk = type=http-response, pattern=^https?:\/\/api.coolapk.com\/v6\/dataList, script-path=https://github.com/ddgksf2013/Scripts/raw/master/coolapk.js, requires-body=true, max-size=-1, timeout=60
coolapk1 = type=http-response, pattern=^https?:\/\/api.coolapk.com\/v6\/feed\/detail, script-path=https://github.com/ddgksf2013/Scripts/raw/master/coolapk.js, requires-body=true, max-size=-1, timeout=60
coolapk2 = type=http-response, pattern=^https?:\/\/api.coolapk.com\/v6\/feed\/replyList, script-path=https://github.com/ddgksf2013/Scripts/raw/master/coolapk.js, requires-body=true, max-size=-1, timeout=60
coolapk3 = type=http-response, pattern=^https?:\/\/api.coolapk.com\/v6\/main\/indexV8, script-path=https://github.com/ddgksf2013/Scripts/raw/master/coolapk.js, requires-body=true, max-size=-1, timeout=60
coolapk4 = type=http-response, pattern=^https?:\/\/api.coolapk.com\/v6\/main\/init, script-path=https://github.com/ddgksf2013/Scripts/raw/master/coolapk.js, requires-body=true, max-size=-1, timeout=60
mygolbus = type=http-response, pattern=https?:\/\/wx\.mygolbs\.com\/WxBusServer\/ApiData\.do, script-path=https://github.com/ddgksf2013/Scripts/raw/master/zhangshanggongjiao.js, requires-body=true, max-size=-1, timeout=60
wechat = type=http-response, pattern=^https?:\/\/mp\.weixin\.qq\.com\/mp\/getappmsgad, script-path=https://raw.githubusercontent.com/NobyDa/Script/master/QuantumultX/File/Wechat.js, requires-body=true, max-size=-1, timeout=60
weibo_json = type=http-response, pattern=^https://api.weibo.cn/2/!/client/light_skin, script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_json1 = type=http-response, pattern=^https://new.vip.weibo.cn/littleskin/preview, script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_json2 = type=http-response, pattern=^https?://(sdk|wb)app\.uve\.weibo\.com(/interface/sdk/sdkad.php|/wbapplua/wbpullad.lua), script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_json3 = type=http-response, pattern=^https?:\/\/api\.weibo\.cn\/\d\/\w{5}\/(statuses_unread_hot_timeline|timeline), script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_json4 = type=http-response, pattern=^https?:\/\/api\.weibo\.cn\/\d\/groups\/allgroups\/v\d, script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_json5 = type=http-response, pattern=^https?:\/\/api\.weibo\.cn\/\d\/video\/tiny_stream_mid_detail, script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_json6 = type=http-response, pattern=^https?:\/\/boot.*weibo\.com\/v\d\/ad\/preload, script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_json7 = type=http-response, pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/(checkin/show|\!/live/media_homelist|comments/build_comments|container/get_item), script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_json8 = type=http-response, pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/(searchall|page\?|messageflow), script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_json9 = type=http-response, pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/\w{5}\/cardlist, script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_json10 = type=http-response, pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/cardlist, script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_json11 = type=http-response, pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/groups/timeline, script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_json12 = type=http-response, pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/profile/(me|container_timeline), script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_json13 = type=http-response, pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/search/(finder|container_timeline|container_discover), script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_json14 = type=http-response, pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/statuses/(container_timeline|unread_hot_timeline|extend|video_mixtimeline|unread_topic_timeline), script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_json15 = type=http-response, pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/statuses/(unread_)?friends(/|_)timeline, script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_json16 = type=http-response, pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/video/(community_tab|remind_info|tiny_stream_video_list), script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_json17 = type=http-response, pattern=^https?:\/\/weibointl\.api\.weibo\.c(n|om)\/portal\.php.*feed&a=trends, script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_json18 = type=http-response, pattern=^https?:\/\/weibointl\.api\.weibo\.c(n|om)\/portal\.php.*get_coopen_ads, script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_json19 = type=http-response, pattern=^https?:\/\/weibointl\.api\.weibo\.cn\/portal\.php\?a=open_app, script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_json20 = type=http-response, pattern=^https?:\/\/weibointl\.api\.weibo\.cn\/portal\.php\?a=search_topic, script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_json21 = type=http-response, pattern=^https?:\/\/weibointl\.api\.weibo\.cn\/portal\.php\?a=user_center, script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_search_info = type=http-request, pattern=^https?:\/\/weibointl\.api\.weibo\.c(n|om)\/portal\.php.*user&a=get_searching_info, script-path=http://script.hub/convert/_start_/https://github.com/ddgksf2013/Scripts/raw/master/weibo_search_info.json/_end_/weibo_search_info.json?type=mock&target-app=shadowrocket-module, timeout=60
weibo_search_topic = type=http-request, pattern=^https?:\/\/weibointl\.api\.weibo\.c(n|om)\/portal\.php.*feed&a=search_topic, script-path=http://script.hub/convert/_start_/https://github.com/ddgksf2013/Scripts/raw/master/weibo_search_topic.json/_end_/weibo_search_topic.json?type=mock&target-app=shadowrocket-module, timeout=60

[MITM]
hostname= %APPEND% ad.12306.cn,api.live.bilibili.com,api.vc.bilibili.com,api.bilibili.com,api.biliapi.net,bbs-api.miyoushe.com,*.bilibili.com,*.bilibili.*,*biliapi.net,manga.bilibili.com,grpc.biliapi.net,mp.weixin.qq.com,-broadcast.chat.bilibili.com,-*cdn*.biliapi.net,-*tracker*.biliapi.net
