#!name=SRConfigs
#!desc=Shadowrocket策略补充

[General]
skip-proxy = %APPEND% captive.apple.com, e.crashlytics.com, gate.lagou.com, login-service.mobile-bank.psbc.com, mobile-bank.psbc.com, seed-sequoia.siri.apple.com, sequoia.apple.com, www.abchina.com.cn, www.baidu.com, www.shanbay.com, wxh.wo.cn, yunbusiness.ccb.com

[Rule]
DOMAIN,ad.12306.cn,DIRECT
DOMAIN-KEYWORD,bing,PROXY
DOMAIN,d.image.i4.cn,REJECT
DOMAIN,hub5btmain.v6.shub.sandai.net,REJECT
DOMAIN,hub5emu.v6.shub.sandai.net,REJECT
DOMAIN,hub5idx.v6.shub.sandai.net,REJECT
DOMAIN,im.tieba.baidu.com,REJECT
DOMAIN,ntb.lanjie100.com,REJECT
DOMAIN-KEYWORD,118.89.204.198,REJECT
DOMAIN-KEYWORD,ad-sign.byteimg.com,REJECT
DOMAIN-KEYWORD,asiad.byteactivity,REJECT
DOMAIN-KEYWORD,baihemob,REJECT
DOMAIN-KEYWORD,beizi.biz,REJECT
DOMAIN-KEYWORD,pglstatp,REJECT
DOMAIN-KEYWORD,video-cn.snssdk.com,REJECT

[URL Rewrite]
^https?:\/\/quanguo\.mygolbs\.com:8081\/MyBusServer\/servlet\/MyGoServer\.HttpPool\.HttpHandlerServlet - REJECT-200 

[Script]
12306 = type=http-request,pattern=^https?:\/\/ad\.12306\.cn\/ad\/ser\/getAdList,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/Runeston/script/main/12306.js
lightroom = type=http-response,pattern=^https:\/\/photos\.adobe\.io\/v2\/accounts*,requires-body=1,script-path=https://raw.githubusercontent.com/litieyin/AD_VIP/main/Script/lightroom.js

[MITM]
hostname= %APPEND% ad.12306.cn, photos.adobe.io
