#!name=SRScripts
#!desc=SR策略补充模块

[General]
skip-proxy = %APPEND% captive.apple.com, e.crashlytics.com, gate.lagou.com, login-service.mobile-bank.psbc.com, mobile-bank.psbc.com, seed-sequoia.siri.apple.com, sequoia.apple.com, www.abchina.com.cn, www.baidu.com, www.shanbay.com, wxh.wo.cn, yunbusiness.ccb.com

[Rule]
DOMAIN,ad.12306.cn,DIRECT
DOMAIN,d.image.i4.cn,REJECT
DOMAIN,hub5btmain.v6.shub.sandai.net,REJECT
DOMAIN,hub5emu.v6.shub.sandai.net,REJECT
DOMAIN,hub5idx.v6.shub.sandai.net,REJECT
DOMAIN,im.tieba.baidu.com,REJECT
DOMAIN,ntb.lanjie100.com,REJECT
DOMAIN-KEYWORD,118.89.204.198,REJECT
DOMAIN-KEYWORD,ad-sign.byteimg.com,REJECT
DOMAIN-KEYWORD,asiad.byteactivity,REJECT
DOMAIN-KEYWORD,baihemob,REJECT
DOMAIN-KEYWORD,beizi.biz,REJECT
DOMAIN-KEYWORD,pglstatp,REJECT
DOMAIN-KEYWORD,video-cn.snssdk.com,REJECT
DOMAIN-KEYWORD,volc,REJECT

[URL Rewrite]
(^https?:\/\/[\w-]+\.googlevideo\.com\/(?!dclk_video_ads).+?)&ctier=L(&.+?),ctier,(.+) $1$2$3 302
^https://api.bilibili.com/pgc/season/player/cards - REJECT-DICT
^https://app.bilibili.com/x/v2/splash/ - REJECT-DICT
^https?:\/\/(app\.bilibili\.com|grpc\.biliapi\.net)\/bilibili\.app\.interface\.v1\.Search\/Default - REJECT
^https?:\/\/(preload-click|preload-impression)\.uve\.weibo\.com\/(interface\/wbpullad\/wbpullad_click\.php|wbapplua\/get_wbpullad_log\.lua) - REJECT
^https?:\/\/(www|s)\.youtube\.com\/(pagead|ptracking) - REJECT-200
^https?:\/\/(www|s)\.youtube\.com\/api\/stats\/ads - REJECT-200
^https?:\/\/[\w-]+\.googlevideo\.com\/(?!(dclk_video_ads|videoplayback\?)).+&oad - REJECT-200
^https?:\/\/api\.bilibili\.com\/pgc\/activity\/deliver\/material\/receive - REJECT-DICT
^https?:\/\/api\.bilibili\.com\/pgc\/season\/player\/ogv\/cards - REJECT-DICT
^https?:\/\/api\.bilibili\.com\/x\/vip\/ads\/material\/report - REJECT-DICT
^https?:\/\/api\.coolapk\.com\/v6\/search\?.*type=hotSearch - REJECT-DICT
^https?:\/\/api\.weibo\.cn\/\d\/!\/huati\/discovery_home_bottom_getdotinfo - REJECT-DICT
^https?:\/\/api\.weibo\.cn\/\d\/ad\/preload - REJECT-DICT
^https?:\/\/api\.weibo\.cn\/\d\/cardlist\?v_f=.*Weibo_intl - REJECT-DICT
^https?:\/\/api\.weibo\.cn\/\d\/profile\/recommend_popuser - REJECT-DICT
^https?:\/\/app\.bilibili\.com\/x\/resource\/ip - REJECT
^https?:\/\/bbs-api\.miyoushe\.com\/apihub\/api\/getAppSplash - REJECT
^https?:\/\/boot.*weibo\.com\/v\d\/ad\/realtime - REJECT-200
^https?:\/\/conf-darwin\.xycdn\.com - REJECT-DICT
^https?:\/\/m?api\.weibo\.c(n|om)\/\d/push/daily - REJECT-DICT
^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/ad\/weibointl\? - REJECT-DICT
^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/hot\/hours_spotlight - REJECT-DICT
^https?:\/\/manga\.bilibili\.com\/twirp\/comic\.v\d\.Comic\/(Flash|ListFlash|GetActivityTab) - REJECT-DICT
^https?:\/\/pan\.baidu\.com\/act\/api\/activityentry - REJECT-200
^https?:\/\/pan\.baidu\.com\/act\/v\d\/(bchannel|welfare)\/list - REJECT-200
^https?:\/\/pan\.baidu\.com\/rest\/.*\/pcs\/ad - REJECT-200
^https?:\/\/quanguo\.mygolbs\.com:8081\/MyBusServer\/servlet\/MyGoServer\.HttpPool\.HttpHandlerServlet - REJECT-200 
^https?:\/\/s\.youtube\.com\/api\/stats\/qoe\?adcontext - REJECT-200
^https?:\/\/sdk1xyajs\.data\.kuiniuca\.com - REJECT
^https?:\/\/sdkapp\.uve\.weibo\.com\/interface\/sdk\/sdkconfig\.php - REJECT
^https?:\/\/weibointl\.api\.weibo\.c(n|om)\/portal\.php\?a=hot_search_users - REJECT-DICT

[Script]
12306 = type=http-request, pattern=^https?:\/\/ad\.12306\.cn\/ad\/ser\/getAdList, script-path=https://raw.githubusercontent.com/sve1r/Rules-For-Quantumult-X/main/Scripts/AdBlock/Other/12306.js, requires-body=true, max-size=-1, timeout=60
baiducloud = type=http-response, pattern=^https?:\/\/pan\.baidu\.com\/api\/getsyscfg, script-path=https://gist.githubusercontent.com/ddgksf2013/f43026707830c7818ee3ba624e383c8d/raw/baiduCloud.vip.js, requires-body=true, max-size=-1, timeout=60
baiducloud = type=http-response, pattern=^https:\/\/pan\.baidu\.com\/rest\/.*\/membership\/user\?app_id, script-path=https://gist.githubusercontent.com/ddgksf2013/f43026707830c7818ee3ba624e383c8d/raw/baiduCloud.vip.js, requires-body=true, max-size=-1, timeout=60
bilibili_json = type=http-response, pattern=^https?:\/\/api\.bili(api|bili)\.(net|com)\/pgc\/season\/app\/related\/recommend\?, script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/bilibili_json.js, requires-body=true, max-size=-1, timeout=60
bilibili_json1 = type=http-response, pattern=^https://app.bilibili.com/x/v2/search/square, script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/bilibili_json.js, requires-body=true, max-size=-1, timeout=60
bilibili_json2 = type=http-response, pattern=^https:\/\/app\.bilibili\.com\/x\/v2\/splash\/list, script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/bilibili_json.js, requires-body=true, max-size=-1, timeout=60
bilibili_json3 = type=http-response, pattern=^https?:\/\/api\.(bilibili|biliapi)\.(com|net)\/pgc\/page\/bangumi, script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/bilibili_json.js, requires-body=true, max-size=-1, timeout=60
bilibili_json4 = type=http-response, pattern=^https?:\/\/api\.(bilibili|biliapi)\.(com|net)\/pgc\/page\/cinema\/tab\?, script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/bilibili_json.js, requires-body=true, max-size=-1, timeout=60
bilibili_json5 = type=http-response, pattern=^https?:\/\/api\.live\.bilibili\.com\/xlive\/app-interface\/v2\/index\/feed, script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/bilibili_json.js, requires-body=true, max-size=-1, timeout=60
bilibili_json6 = type=http-response, pattern=^https?:\/\/api\.live\.bilibili\.com\/xlive\/app-room\/v1\/index\/getInfoByRoom, script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/bilibili_json.js, requires-body=true, max-size=-1, timeout=60
bilibili_json7 = type=http-response, pattern=^https?:\/\/api\.live\.bilibili\.com\/xlive\/e-commerce-interface\/v\d\/ecommerce-user\/get_shopping_info\?, script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/bilibili_json.js, requires-body=true, max-size=-1, timeout=60
bilibili_json8 = type=http-response, pattern=^https?:\/\/app\.bilibili\.com\/x\/resource\/show\/tab, script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/bilibili_json.js, requires-body=true, max-size=-1, timeout=60
bilibili_json9 = type=http-response, pattern=^https?:\/\/app\.bilibili\.com\/x\/resource\/top\/activity, script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/bilibili_json.js, requires-body=true, max-size=-1, timeout=60
bilibili_json10 = type=http-response, pattern=^https?:\/\/app\.bilibili\.com\/x\/v2\/account\/mine, script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/bilibili_json.js, requires-body=true, max-size=-1, timeout=60
bilibili_json11 = type=http-response, pattern=^https?:\/\/app\.bilibili\.com\/x\/v2\/account\/myinfo\?, script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/bilibili_json.js, requires-body=true, max-size=-1, timeout=60
bilibili_json12 = type=http-response, pattern=^https?:\/\/app\.bilibili\.com\/x\/v2\/feed\/index, script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/bilibili_json.js, requires-body=true, max-size=-1, timeout=60
bilibili_proto_beta = type=http-response, pattern=^https:\/\/(grpc\.biliapi\.net|app\.bilibili\.com)\/bilibili\.app\.interface\.v1\.Teenagers\/ModeStatus, script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/bilibili_proto_beta.js, requires-body=true, binary-body-mode=true, max-size=-1, timeout=60
bilibili_proto_beta1 = type=http-response, pattern=^https?:\/\/(app\.bilibili\.com|grpc\.biliapi\.net)\/bilibili\.app\.(view|viewunite)\.v1\.View\/(View|TFInfo)$, script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/bilibili_proto_beta.js, requires-body=true, binary-body-mode=true, max-size=-1, timeout=60
bilibili_proto_beta2 = type=http-response, pattern=^https?:\/\/(app\.bilibili\.com|grpc\.biliapi\.net)\/bilibili\.app\.dynamic\.v2\.Dynamic\/Dyn(All|Video)$, script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/bilibili_proto_beta.js, requires-body=true, binary-body-mode=true, max-size=-1, timeout=60
bilibili_proto_beta3 = type=http-response, pattern=^https?:\/\/(app\.bilibili\.com|grpc\.biliapi\.net)\/bilibili\.community\.service\.dm\.v1\.DM\/(DmView|DmSegMobile), script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/bilibili_proto_beta.js, requires-body=true, binary-body-mode=true, max-size=-1, timeout=60
bilibili_proto_beta4 = type=http-response, pattern=^https?:\/\/(grpc\.biliapi\.net|app\.bilibili\.com)\/bilibili\.polymer\.app\.search\.v1\.Search\/SearchAll$, script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/bilibili_proto_beta.js, requires-body=true, binary-body-mode=true, max-size=-1, timeout=60
coolapk = type=http-response, pattern=^https?:\/\/api.coolapk.com\/v6\/dataList, script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/coolapk.js, requires-body=true, max-size=-1, timeout=60
coolapk1 = type=http-response, pattern=^https?:\/\/api.coolapk.com\/v6\/feed\/detail, script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/coolapk.js, requires-body=true, max-size=-1, timeout=60
coolapk2 = type=http-response, pattern=^https?:\/\/api.coolapk.com\/v6\/feed\/replyList, script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/coolapk.js, requires-body=true, max-size=-1, timeout=60
coolapk3 = type=http-response, pattern=^https?:\/\/api.coolapk.com\/v6\/main\/indexV8, script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/coolapk.js, requires-body=true, max-size=-1, timeout=60
coolapk4 = type=http-response, pattern=^https?:\/\/api.coolapk.com\/v6\/main\/init, script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/coolapk.js, requires-body=true, max-size=-1, timeout=60
flightradar24=type=http-response,pattern=^https://mobile.flightradar24.com/mobile/(user-session|subscribe),requires-body=1,script-path=https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/scripts/Flightradar24.js
lightroom = type=http-response,pattern=^https:\/\/photos\.adobe\.io\/v2\/accounts*,requires-body=1,script-path=https://raw.githubusercontent.com/litieyin/AD_VIP/main/Script/lightroom.js
mygolbus = type=http-response, pattern=https?:\/\/wx\.mygolbs\.com\/WxBusServer\/ApiData\.do, script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/zhangshanggongjiao.js, requires-body=true, max-size=-1, timeout=60
spotify_json = type=http-request,pattern=^https:\/\/spclient\.wg\.spotify\.com\/(artistview\/v1\/artist|album-entity-view\/v2\/album)\/,requires-body=0,script-path=https://raw.githubusercontent.com/app2smile/rules/master/js/spotify-json.js
spotify_proto = type=http-response,pattern=^https:\/\/spclient\.wg\.spotify\.com\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$,requires-body=1,binary-body-mode=1,max-size=0,script-path=https://raw.githubusercontent.com/app2smile/rules/master/js/spotify-proto.js,script-update-interval=0
wechat = type=http-response, pattern=^https?:\/\/mp\.weixin\.qq\.com\/mp\/getappmsgad, script-path=https://raw.githubusercontent.com/NobyDa/Script/master/QuantumultX/File/Wechat.js, requires-body=true, max-size=-1, timeout=60
weibo_json = type=http-response, pattern=^https://api.weibo.cn/2/!/client/light_skin, script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_json1 = type=http-response, pattern=^https://new.vip.weibo.cn/littleskin/preview, script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_json2 = type=http-response, pattern=^https?://(sdk|wb)app\.uve\.weibo\.com(/interface/sdk/sdkad.php|/wbapplua/wbpullad.lua), script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_json3 = type=http-response, pattern=^https?:\/\/api\.weibo\.cn\/\d\/\w{5}\/(statuses_unread_hot_timeline|timeline), script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_json4 = type=http-response, pattern=^https?:\/\/api\.weibo\.cn\/\d\/groups\/allgroups\/v\d, script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_json5 = type=http-response, pattern=^https?:\/\/api\.weibo\.cn\/\d\/video\/tiny_stream_mid_detail, script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_json6 = type=http-response, pattern=^https?:\/\/boot.*weibo\.com\/v\d\/ad\/preload, script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_json7 = type=http-response, pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/(checkin/show|\!/live/media_homelist|comments/build_comments|container/get_item), script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_json8 = type=http-response, pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/(searchall|page\?|messageflow), script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_json9 = type=http-response, pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/\w{5}\/cardlist, script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_json10 = type=http-response, pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/cardlist, script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_json11 = type=http-response, pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/groups/timeline, script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_json12 = type=http-response, pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/profile/(me|container_timeline), script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_json13 = type=http-response, pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/search/(finder|container_timeline|container_discover), script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_json14 = type=http-response, pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/statuses/(container_timeline|unread_hot_timeline|extend|video_mixtimeline|unread_topic_timeline), script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_json15 = type=http-response, pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/statuses/(unread_)?friends(/|_)timeline, script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_json16 = type=http-response, pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/video/(community_tab|remind_info|tiny_stream_video_list), script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_json17 = type=http-response, pattern=^https?:\/\/weibointl\.api\.weibo\.c(n|om)\/portal\.php.*feed&a=trends, script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_json18 = type=http-response, pattern=^https?:\/\/weibointl\.api\.weibo\.c(n|om)\/portal\.php.*get_coopen_ads, script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_json19 = type=http-response, pattern=^https?:\/\/weibointl\.api\.weibo\.cn\/portal\.php\?a=open_app, script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_json20 = type=http-response, pattern=^https?:\/\/weibointl\.api\.weibo\.cn\/portal\.php\?a=search_topic, script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_json21 = type=http-response, pattern=^https?:\/\/weibointl\.api\.weibo\.cn\/portal\.php\?a=user_center, script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/weibo_json.js, requires-body=true, max-size=-1, timeout=60
weibo_search_info = type=http-request, pattern=^https?:\/\/weibointl\.api\.weibo\.c(n|om)\/portal\.php.*user&a=get_searching_info, script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/weibo_search_info.json, timeout=60
weibo_search_topic = type=http-request, pattern=^https?:\/\/weibointl\.api\.weibo\.c(n|om)\/portal\.php.*feed&a=search_topic, script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/weibo_search_topic.json, timeout=60
youtube_request_beta = type=http-request, pattern=^https?:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/(browse|next|player|reel\/reel_watch_sequence), script-path=https://raw.githubusercontent.com/Maasea/sgmodule/master/Script/Youtube/dist/youtube.request.beta.js, requires-body=true, binary-body-mode=true, max-size=-1, timeout=60
youtube_response_beta = type=http-response, pattern=^https?:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/(browse|next|player|search|reel\/reel_watch_sequence|guide|account\/get_setting), script-path=https://raw.githubusercontent.com/Maasea/sgmodule/master/Script/Youtube/dist/youtube.response.beta.js, requires-body=true, binary-body-mode=true, max-size=-1, timeout=60

[MITM]
hostname= %APPEND% ad.12306.cn, api.live.bilibili.com, api.vc.bilibili.com, api.bilibili.com, api.biliapi.net, bbs-api.miyoushe.com, *.bilibili.com, *.bilibili.*, *biliapi.net, *.googlevideo.com, manga.bilibili.com, grpc.biliapi.net, mobile.flightradar24.com, mp.weixin.qq.com, pan.baidu.com, photos.adobe.io, s.youtube.com, spclient.wg.spotify.com, www.youtube.com, youtubei.googleapis.com, -broadcast.chat.bilibili.com, -*cdn*.biliapi.net, -redirector*.googlevideo.com, -*tracker*.biliapi.net
